/*
 * Copyright 2025 Mifos Initiative
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * See See https://github.com/openMF/kmp-project-template/blob/main/LICENSE
 */
package org.mifosx.openbanking.core.database

import androidx.room3.AutoMigration
import androidx.room3.ConstructedBy
import androidx.room3.Database
import androidx.room3.RoomDatabase
import androidx.room3.RoomDatabaseConstructor
import org.mifosx.openbanking.core.database.cache.ObpCacheDao
import org.mifosx.openbanking.core.database.cache.ObpCacheEntity
import org.mifosx.openbanking.core.database.infra.dao.BookkeeperDao
import org.mifosx.openbanking.core.database.infra.dao.DraftDao
import org.mifosx.openbanking.core.database.infra.dao.FetchedAtDao
import org.mifosx.openbanking.core.database.infra.entity.BookkeeperEntity
import org.mifosx.openbanking.core.database.infra.entity.DraftEntity
import org.mifosx.openbanking.core.database.infra.entity.FetchedAtEntity
import org.mifosx.openbanking.core.database.sample.dao.SampleDao
import org.mifosx.openbanking.core.database.sample.entity.SampleEntity

/**
 * KSP-generated constructor bridge for [AppDatabase].
 *
 * Room 3 requires an `expect object` annotated via [@ConstructedBy][ConstructedBy] so that
 * the KSP compiler plugin can generate a platform-specific `actual object` containing the
 * `AppDatabase_Impl` instantiation logic.
 */
expect object AppDatabaseConstructor : RoomDatabaseConstructor<AppDatabase> {
    override fun initialize(): AppDatabase
}

/**
 * Root Room 3 database for the application.
 *
 * This is a **commonMain** definition that works across all Kotlin Multiplatform targets
 * (Android, Desktop/JVM, iOS/Native, JS, WasmJS). Platform-specific database creation
 * is handled by [template.core.base.database.AppDatabaseFactory] in each platform's
 * DI module — see [org.mifosx.openbanking.core.database.di.DatabaseModule].
 *
 * Room 3 uses the [ConstructedBy] annotation to delegate instance creation to
 * [AppDatabaseConstructor], whose `actual` implementation is generated by KSP on
 * every target.
 *
 * @see org.mifosx.openbanking.core.database.sample.dao.SampleDao
 * @see org.mifosx.openbanking.core.database.sample.entity.SampleEntity
 */
@Database(
    entities = [
        SampleEntity::class,
        BookkeeperEntity::class,
        FetchedAtEntity::class,
        DraftEntity::class,
        ObpCacheEntity::class,
    ],
    version = AppDatabase.VERSION,
    exportSchema = true,
    autoMigrations = [
        AutoMigration(from = 1, to = 2),
    ],
)
@ConstructedBy(AppDatabaseConstructor::class)
abstract class AppDatabase : RoomDatabase() {

    abstract val sampleDao: SampleDao
    abstract val bookkeeperDao: BookkeeperDao
    abstract val fetchedAtDao: FetchedAtDao
    abstract val draftDao: DraftDao
    abstract val obpCacheDao: ObpCacheDao

    companion object {
        const val VERSION = 2
        const val DATABASE_NAME = "mifos_database.db"
    }
}
